name: mygemini
description: "MyGemini is an AI App based on ChatGPT developed by Lucas Maia Dantas"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  google_generative_ai: ^0.4.3
  shared_preferences: ^2.0.15
  lottie: ^3.1.2
  hive: ^2.2.3
  path_provider: ^2.1.0
  get: ^4.6.6
  flutter_animate: ^4.5.0
  http: ^1.1.0
  cached_network_image: ^3.4.1
  share_plus: ^10.0.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  syncfusion_flutter_pdf: ^26.2.14
  flutter_markdown: ^0.7.3+1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.0.0
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - .env
